# -*- coding: utf-8 -*-
"""Streamlit_qGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MKylJtRwKZrUzPxrjWC2wSDXxeljdSN
"""
import streamlit as st
import numpy as np
import joblib

# -------------------------------
# LOAD MODEL
# -------------------------------
model = joblib.load("xgb_qgan.pkl")

# -------------------------------
# UI
# -------------------------------
st.title("Quantum Fraud Detection")

st.write("Enter PCA values (PC1 to PC6)")

# Inputs (PCA values)
pc1 = st.number_input("PC1", value=0.0)
pc2 = st.number_input("PC2", value=0.0)
pc3 = st.number_input("PC3", value=0.0)
pc4 = st.number_input("PC4", value=0.0)
pc5 = st.number_input("PC5", value=0.0)
pc6 = st.number_input("PC6", value=0.0)

# -------------------------------
# PREDICTION
# -------------------------------
if st.button("Predict Fraud"):

    X = np.array([[pc1, pc2, pc3, pc4, pc5, pc6]])

    prob = model.predict_proba(X)[0][1]

    st.subheader("Result")
    st.write("Fraud probability:", round(prob, 3))

    if prob > 0.5:
        st.error("High Fraud Risk")
    else:
        st.success("Low Fraud Risk")


# -------------------------------
# EXAMPLES
# -------------------------------
st.write("### Try Examples")

if st.button("Normal Example"):
    example = np.array([[0.1, -0.2, 0.05, -0.1, 0.2, -0.05]])
    prob = model.predict_proba(example)[0][1]
    st.write("Fraud probability:", round(prob, 3))
    st.success("Normal")

if st.button("Fraud Example"):
    example = np.array([[1.2, -1.5, 0.8, 0.6, -0.9, 0.7]])
    prob = model.predict_proba(example)[0][1]
    st.write("Fraud probability:", round(prob, 3))
    st.error("Fraud")

